game_name : rock_paper_scissor
game_config :
  payoff_matrix:
  - [[0, 0], [1, -1], [-1, 1]]
  - [[-1, 1], [0, 0], [1, -1]]
  - [[1, -1], [-1, 1], [0, 0]]

initial_joint_policy:
  - - 0.8
    - 0.1
    - 0.1
  - - 0.1
    - 0.8
    - 0.1