algo_name : IL-Forel
algo_config :

  # ============ ForeL parameters ============
  forel_config:
    dynamics_method : 
      method : rd
      learning_rate_rd : 0.001
    q_value_estimation_method : 
      method : mc
      n_monte_carlo_q_evaluation : 20
      learning_rate_q_values : 0.01   # if using mc_inc

  # ============ Iterated Lyapunov FoReL parameters ===========
  n_timesteps_per_iterations : 4000
  do_mu_update : True
  do_linear_interpolation_mu : False
  eta_scheduler_config:
    class_string : core.scheduler:Constant
    value : 1
  do_set_NE_as_init_mu : False  # use Nash equilibrium as initial mu (for experimental purposes)
    
    