algo_name : PAL-FoReL
algo_config :
  # ============ ForeL parameters ============
  forel_config:
    q_value_estimation_method : model-based
    dynamics_method : rd
    learning_rate_rd : 0.001
    learning_rate_cum_values : 0.001
    n_monte_carlo_q_evaluation : 20
    regularizer : entropy
  
  # ============ Population Alternating Lyapunov FoReL parameters ===========

  # How many timesteps to do for each phase
  n_timesteps_pc_phase : 5000
  n_timesteps_lyapunov_phase : 5000

  # The method to use to update the population, either "geometric" or "arithmetic"
  population_averaging : "arithmetic"
  
  # The sampler method and its configuration. Method is either "random", "periodic" or "last" (equivalent to I-FoReL)
  sampler_population:
    method : "random"
    # method : "periodic"
    # method : "last"
    size_population : 100
    n_last_policies_to_sample : 10000
    distribution : "uniform"

  # The eta scheduler configuration
  eta_scheduler_config:
    class_string : core.scheduler:SquareWave
    max_value : 1
    min_value : 0
    steps_at_min : ${algo.algo_config.n_timesteps_pc_phase}
    steps_at_max : ${algo.algo_config.n_timesteps_lyapunov_phase}
    start_at_max : False