algo_name : PIL-FoReL
algo_config :
  # ============ ForeL parameters ============
  forel_config:
    q_value_estimation_method : model-based
    dynamics_method : rd
    learning_rate_rd : 0.001
    learning_rate_cum_values : 0.001
    n_monte_carlo_q_evaluation : 20
    regularizer : entropy
  


  # ============ Population parameters ============
  # The method to use to update the population, either "geometric" or "arithmetic"
  population_averaging : "arithmetic"

  # The sampler method and its configuration. Method is either "random", "periodic" or "last" (equivalent to I-FoReL)
  sampler_population:
    method : "random"
    # method : "periodic"
    # method : "last"
    size_population : 100
    n_last_policies_to_sample : 10000
    distribution : "uniform"



  # ============ Population Iterated Lyapunov FoReL parameters ===========
  # How many timesteps to do before updating the population
  n_timesteps_per_iterations : 10000
  
  # The eta scheduler configuration
  eta_scheduler_config:
    class_string : core.scheduler:Constant
    value : 1