algo_name : PIL-FoReL
algo_config :
  # ============ ForeL parameters ============
  forel_config:
    dynamics_method : 
      method : rd
      learning_rate_rd : 0.001
    q_value_estimation_method : 
      method : model-based
  


  # ============ Population parameters ============
  # The method to use to update the population, either "geometric" or "arithmetic"
  population_averaging : "arithmetic"
  
  # The number of policies to sample from last policies. If None/unspeficied, all policies will be candidates.
  n_last_policies_to_sample : 10000

  # The sampler method and its configuration. Method is either "random", "periodic" or "last" (equivalent to I-FoReL)
  sampler_population:
    method : "random"
    size_population : 100
    distribution : "uniform"



  # ============ Population Iterated Lyapunov FoReL parameters ===========
  # How many timesteps to do before updating the population
  n_timesteps_per_iterations : 10000
  
  # The eta scheduler configuration
  eta_scheduler_config:
    class_string : core.scheduler:Constant
    value : 1