algo_name : PIL_FoReL
algo_config :
  # ============ ForeL parameters ============
  forel_config:
    q_value_estimation_method : model-based
    dynamics_method : rd
    learning_rate_rd : 0.001
    learning_rate_cum_values : 0.001
    n_monte_carlo_q_evaluation : 20
    regularizer : entropy
  
  # ============ Population Iterated Lyapunov FoReL parameters ===========

  # How many timesteps to do before updating the population
  n_timesteps_per_iterations : 10000

  # The method to use to update the population, either "geometric" or "arithmetic"
  population_averaging : "arithmetic"
  
  # The sampler method and its configuration. Method is either "random" or "periodic"
  sampler_population:
    method : "periodic"
    # The size of the population sampled
    size_population : 100
    # The number of policies to sample from last policies. If None/unspeficied, all policies will be candidates.
    n_last_policies_to_sample : 10000

  # The eta scheduler configuration
  eta_scheduler_config:
    type : constant    # use 'constant' if mu changes through training
    start_value : 1
    end_value : 0.05
    n_steps : 50000