# Training configuration for inRL
n_episodes_training: 1000000
seed: Null

# Display information
frequency_metric : 9999
do_cli : True
frequency_cli : 99999
do_tb : True
do_wandb : False
wandb_config:
  project : Algorithms-for-Normal-Form-Games
plot_config :
  do_plot_online : True
  frequency_plot : 1000
  frequency_points_plot : 100
tqdm_bar : True



defaults:
  - algo : forel
  - game : mp_bias
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .