# Training configuration for inRL
seed: Null
verbose: 2
tqdm_bar : True
do_wandb: True
do_tb : True
do_cli : False
do_plot : True
n_episodes_training: 100000




defaults:
  - algo : iforel
  - game : mp
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .